#!/usr/bin/env bash

# Log file for debugging
LOG_FILE="$HOME/setup_log.txt"

# Function to check and create directories
create_directory() { 
  local dir_path=$1 # stores the path into a local variable
  if [ ! -d "$dir_path" ]; then # checks to see if the variable exists and is a directory
    mkdir -p "$dir_path" && echo "Directory $dir_path created" >> "$LOG_FILE" || echo "Failed to create directory $dir_path" >> "$LOG_FILE" # creates the directory and outputs if it succedded or failed
  else
    echo "Directory $dir_path already exists" >> "$LOG_FILE" # if it exists then outputs the message
  fi
}
# Function to create symliinks
create_symlink() {
  local target=$1 # stores "target" into a local variable
  local link_name=$2 # stores "link_name" into a local variable
  if [ -L "$link_name" ]; then #  checks if it is a symbolic link
    echo "Symlink $link_name already exists" >> "$LOG_FILE" # if it is a symbolic link then outputs the message
  else
    ln -s "$target" "$link_name" && echo "Symlink $link_name created" >> "$LOG_FILE" || echo "Failed to create symlink $link_name" >> "$LOG_FILE" # creates the symbolic link and outputs if it succedded or failed
  fi
}
