#!user/bin/bash/env bash

#Filename: user_creation


# Check if the script is running with root privileges
if [[ $EUID -ne 0 ]]; then
  echo "Error occured, please run the script as root!"  #  Displays the error message if the script isnt run as root
  exit 1  # Exit the script with exit code 1
fi


usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help           Show this help message and exit"
    echo "  -u, --uid            Shows the userid for the new user"
    echo "  -s, --shell          Shows the shell for the new user"
    echo "  -d, --home-dir       Shows the home directory for the new user"
    echo "  -g, --groups         Shows additional groups for the new user"
    echo ""
    exit 1 # Exits the script with code 1
}


while getopts ":husdg" opt; do
  case $opt in
    h)
      usage
      ;;
    u)
      userid=$OPTARG
      ;;
    s)
      shell=$OPTARG
      ;;
    d)
      home_dir=$OPTARG
      ;;
    g)
      groups=$OPTARG
      ;;
    ?)
      echo "Invalid option: -$OPTARG"
      usage
      ;;
  esac
done


